version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install pytest
  pre_build:
    commands:
      - echo nothing to see here
  build:
    commands:
      - pytest funniest3535.test_joke.py
  post_build:
    commands:
      - echo nothing to see here
artifacts:
  files:
    - setup.py
    - funniest3535/*