version: 0.2

phases:
  install:
    commands:
      - pip install pytest
  pre_build:
    commands:
      - echo nothing to see here
  build:
    commands:
      - pytest test_joke.py
  post_build:
    commands:
      - echo nothing to see here
artifacts:
  files:
    - setup.py
    - funniest3535/*